### PR TITLE
Lint style

### PR DESCRIPTION
**Pull request by halton**

### CODE REVIEW

**Comment by halton** [comment]
@huningxin PTAL.

**Comment by huningxin** [comment]
Is it fixed by you or cherry-picked from upstream? Or can it be cherry-picked from upstream?

**Comment by halton** [comment]
The fix are by me. Do you suggest me to fix in crosswalk (***upstream***) first and pick up here?

**Comment by halton** [comment]
BTW, the upstream lint.py is unix format, and it has copyright already, maybe other minor differences as well.

**Comment by huningxin** [comment]
IMO, it would be good to use Crosswalk lint.py. Do you know why are they different?

**Comment by huningxin** [comment]
Talked with @halton . I got to know the differences are js linter and appveyor buildbot integration. These features are for realsense extensions but  crosswalk. It makes sense to keep them here.

So LGTM. And will merge. Thanks!

**Pull request merged**
