### PR TITLE
[Win] Remove workaround for GN build

### PR DESCRIPTION
**Pull request by halton**

### CODE REVIEW

**Comment by halton** [comment]
@huningxin This PR contains two CL cherry-picked from upstream, thus the .bat is not needed. The last commit is to remove it. PTAL

**Comment by halton** [comment]
@huningxin please review.

**Comment by huningxin** [comment]
LGTM. Merging.

**Comment by huningxin** [comment]
@halton , after merge this PR. the AppVeyor bot fails to build: https://ci.appveyor.com/project/recbuilder/realsense-extensions-crosswalk/build/0.5.1.270

And the same failure for my local build.

Any thoughts?

**Comment by halton** [comment]
Let me check

**Comment by huningxin** [comment]
It seems developer need to set `GYP_MSVS_VERSION` explicitly.

We need to fix that in appveyor.xml and update the wiki.

**Comment by halton** [comment]
`GYP_MSVS_VERSION` should not be needed be set, you could use that workaround for now, I'll figure out root cause.

**Comment by huningxin** [comment]
OK.

**Pull request merged**
