### PR TITLE
[Lint] Add support to ignore files.

### PR DESCRIPTION
**Pull request by halton**
--ignore-file allows to pass a file that specific ignore file list. By
default, the .lintignore under working directory will be used.

### CODE REVIEW

**Comment by halton** [comment]
@huningxin PTAL

**Comment by huningxin** [comment]
Could it support ignoring directory?

**Comment by halton** [comment]
Currently, not yet. It should be not so hard, I can make change to add it.

**Comment by huningxin** [comment]
Thanks.

**Comment by halton** [comment]
@huningxin now the dir ignore feature is added. One line (`sample/src/libs`) in `src/extensions/.lintignore` will do the magic.

**Comment by huningxin** [comment]
LGTM. Thanks for this cool feature.

**Pull request merged**
