### PR TITLE
[IDL Generator] Fix the enum namespace issue of initializer generation

### PR DESCRIPTION
**Pull request by huningxin**
This is partially backport of https://chromium.googlesource.com/chromium/src/+/00f1fc22bfcc653b47d62778170af3eee9855720

Please drop this when rebasing to Chromium.

### CODE REVIEW

**Comment by huningxin** [comment]
@halton , please take a look. Thanks!

**Comment by halton** [comment]
LGTM, merging.

**Comment by halton** [comment]
Sorry I do not have merging permission, I'll sync with @baleboy

**Comment by huningxin** [comment]
do you mind I merge it?

**Comment by halton** [comment]
Yes, please if you have permission?

**Pull request merged**
